logging:
  level:
    root: debug
    #去掉多余日志信息
logging.level:
  org.springframework.boot.autoconfigure: error
  #配置thymeleaf日志级别
  org:
    thymeleaf:
      TemplateEngine:
        CONFIG: info
server:
  port: 8082
spring:
  redis:
    host: 192.168.88.3
    port: 7001
  rabbitmq:
    host: 192.168.88.7
    username: seckill
    password: seckill
    virtual-host: /seckill
    listener:
      simple:
        acknowledge-mode: manual #手动确认
        concurrency: 1 #指定最小的消费者数量
        max-concurrency: 1 #指定最大的消费者数量
    template:
      retry:
        enabled: true
        initial-interval: 10000ms
        max-interval: 80000ms
        multiplier: 2
    publisher-confirm-type: correlated
    publisher-returns: true #消息发送到交换机确认机制,是否确认回调
  thymeleaf:
    check-template: false
    check-template-location: false
    prefix: classpath:/templates/
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@192.168.88.5:1521:orcl
#    url: jdbc:oracle:thin:@192.168.1.22:1521:orcl11g
    username: GST
    password: GST
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
#    jndi-name: java:jboss/jdbc/oracleDS

