logging:
  level:
    root: debug
    #去掉多余日志信息
logging.level:
  org.springframework.boot.autoconfigure: error
  #配置thymeleaf日志级别
  org:
    thymeleaf:
      TemplateEngine:
        CONFIG: info
server:
  port: 8082
spring:
  redis:
    timeout: 6000ms
    password:
    cluster:
      max-redirects: 3  # 获取失败 最大重定向次数
      nodes:
        - 192.168.88.3:7001
        - 192.168.88.3:7002
        - 192.168.88.4:7003
        - 192.168.88.4:7004
        - 192.168.88.6:7005
        - 192.168.88.6:7006
    lettuce:
      pool:
        max-active: 1000  #连接池最大连接数（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 5 # 连接池中的最小空闲连接
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
  rabbitmq:
    host: 192.168.88.7
    username: seckill
    password: seckill
    virtual-host: /seckill
    listener:
      simple:
        acknowledge-mode: manual #手动确认
        concurrency: 1 #指定最小的消费者数量
        max-concurrency: 1 #指定最大的消费者数量
    template:
      retry:
        enabled: true
        initial-interval: 10000ms
        max-interval: 80000ms
        multiplier: 100
    publisher-confirm-type: correlated
    publisher-returns: true #消息发送到交换机确认机制,是否确认回调
  thymeleaf:
    check-template: false
    check-template-location: false
    prefix: classpath:/templates/
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@192.168.88.5:1521:orcl
#    url: jdbc:oracle:thin:@192.168.1.22:1521:orcl11g
    username: GST
    password: GST
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
#    jndi-name: java:jboss/jdbc/oracleDS
